name: walkguide
description: "시각장애인 보조보행 앱"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  pedometer: ^4.0.1
  permission_handler: ^11.0.1
  sensors_plus: ^3.0.0   # ← 이 줄 추가!

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
